// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: remotesignerrpc/remotesigner.proto

package remotesignerrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WhitelistAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Address to add to the whitelist.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// The amount to whitelist for the address.
	Amount int64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *WhitelistAddressRequest) Reset() {
	*x = WhitelistAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhitelistAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistAddressRequest) ProtoMessage() {}

func (x *WhitelistAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistAddressRequest.ProtoReflect.Descriptor instead.
func (*WhitelistAddressRequest) Descriptor() ([]byte, []int) {
	return file_remotesignerrpc_remotesigner_proto_rawDescGZIP(), []int{0}
}

func (x *WhitelistAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WhitelistAddressRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type WhitelistAddressResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WhitelistAddressResp) Reset() {
	*x = WhitelistAddressResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhitelistAddressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistAddressResp) ProtoMessage() {}

func (x *WhitelistAddressResp) ProtoReflect() protoreflect.Message {
	mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistAddressResp.ProtoReflect.Descriptor instead.
func (*WhitelistAddressResp) Descriptor() ([]byte, []int) {
	return file_remotesignerrpc_remotesigner_proto_rawDescGZIP(), []int{1}
}

type WhitelistedAddressesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WhitelistedAddressesRequest) Reset() {
	*x = WhitelistedAddressesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhitelistedAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistedAddressesRequest) ProtoMessage() {}

func (x *WhitelistedAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistedAddressesRequest.ProtoReflect.Descriptor instead.
func (*WhitelistedAddressesRequest) Descriptor() ([]byte, []int) {
	return file_remotesignerrpc_remotesigner_proto_rawDescGZIP(), []int{2}
}

type WhitelistedAddressesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of whitelisted addresses.
	Addresses []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (x *WhitelistedAddressesResp) Reset() {
	*x = WhitelistedAddressesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhitelistedAddressesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistedAddressesResp) ProtoMessage() {}

func (x *WhitelistedAddressesResp) ProtoReflect() protoreflect.Message {
	mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistedAddressesResp.ProtoReflect.Descriptor instead.
func (*WhitelistedAddressesResp) Descriptor() ([]byte, []int) {
	return file_remotesignerrpc_remotesigner_proto_rawDescGZIP(), []int{3}
}

func (x *WhitelistedAddressesResp) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type RemoveWhitelistAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Address to remove from the whitelist.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *RemoveWhitelistAddressRequest) Reset() {
	*x = RemoveWhitelistAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveWhitelistAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWhitelistAddressRequest) ProtoMessage() {}

func (x *RemoveWhitelistAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWhitelistAddressRequest.ProtoReflect.Descriptor instead.
func (*RemoveWhitelistAddressRequest) Descriptor() ([]byte, []int) {
	return file_remotesignerrpc_remotesigner_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveWhitelistAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RemoveWhitelistAddressResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The returned bool is True if the address was removed from the whitelist.
	Removed bool `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
}

func (x *RemoveWhitelistAddressResp) Reset() {
	*x = RemoveWhitelistAddressResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveWhitelistAddressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWhitelistAddressResp) ProtoMessage() {}

func (x *RemoveWhitelistAddressResp) ProtoReflect() protoreflect.Message {
	mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWhitelistAddressResp.ProtoReflect.Descriptor instead.
func (*RemoveWhitelistAddressResp) Descriptor() ([]byte, []int) {
	return file_remotesignerrpc_remotesigner_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveWhitelistAddressResp) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type WhitelistPaymentHashRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Payment hash to add to the whitelist.
	PaymentHash []byte `protobuf:"bytes,1,opt,name=payment_hash,json=paymentHash,proto3" json:"payment_hash,omitempty"`
	// The amount to whitelist for the payment hash.
	Amount int64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *WhitelistPaymentHashRequest) Reset() {
	*x = WhitelistPaymentHashRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhitelistPaymentHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistPaymentHashRequest) ProtoMessage() {}

func (x *WhitelistPaymentHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistPaymentHashRequest.ProtoReflect.Descriptor instead.
func (*WhitelistPaymentHashRequest) Descriptor() ([]byte, []int) {
	return file_remotesignerrpc_remotesigner_proto_rawDescGZIP(), []int{6}
}

func (x *WhitelistPaymentHashRequest) GetPaymentHash() []byte {
	if x != nil {
		return x.PaymentHash
	}
	return nil
}

func (x *WhitelistPaymentHashRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type WhitelistPaymentHashResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WhitelistPaymentHashResp) Reset() {
	*x = WhitelistPaymentHashResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhitelistPaymentHashResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistPaymentHashResp) ProtoMessage() {}

func (x *WhitelistPaymentHashResp) ProtoReflect() protoreflect.Message {
	mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistPaymentHashResp.ProtoReflect.Descriptor instead.
func (*WhitelistPaymentHashResp) Descriptor() ([]byte, []int) {
	return file_remotesignerrpc_remotesigner_proto_rawDescGZIP(), []int{7}
}

type WhitelistedPaymentHashesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WhitelistedPaymentHashesRequest) Reset() {
	*x = WhitelistedPaymentHashesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhitelistedPaymentHashesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistedPaymentHashesRequest) ProtoMessage() {}

func (x *WhitelistedPaymentHashesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistedPaymentHashesRequest.ProtoReflect.Descriptor instead.
func (*WhitelistedPaymentHashesRequest) Descriptor() ([]byte, []int) {
	return file_remotesignerrpc_remotesigner_proto_rawDescGZIP(), []int{8}
}

type WhitelistedPaymentHashesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of whitelisted payment hashes.
	PaymentHashes [][]byte `protobuf:"bytes,1,rep,name=payment_hashes,json=paymentHashes,proto3" json:"payment_hashes,omitempty"`
}

func (x *WhitelistedPaymentHashesResp) Reset() {
	*x = WhitelistedPaymentHashesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhitelistedPaymentHashesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistedPaymentHashesResp) ProtoMessage() {}

func (x *WhitelistedPaymentHashesResp) ProtoReflect() protoreflect.Message {
	mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistedPaymentHashesResp.ProtoReflect.Descriptor instead.
func (*WhitelistedPaymentHashesResp) Descriptor() ([]byte, []int) {
	return file_remotesignerrpc_remotesigner_proto_rawDescGZIP(), []int{9}
}

func (x *WhitelistedPaymentHashesResp) GetPaymentHashes() [][]byte {
	if x != nil {
		return x.PaymentHashes
	}
	return nil
}

type RemoveWhitelistPaymentHashRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Payment hash to remove from the whitelist.
	PaymentHash []byte `protobuf:"bytes,1,opt,name=payment_hash,json=paymentHash,proto3" json:"payment_hash,omitempty"`
}

func (x *RemoveWhitelistPaymentHashRequest) Reset() {
	*x = RemoveWhitelistPaymentHashRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveWhitelistPaymentHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWhitelistPaymentHashRequest) ProtoMessage() {}

func (x *RemoveWhitelistPaymentHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWhitelistPaymentHashRequest.ProtoReflect.Descriptor instead.
func (*RemoveWhitelistPaymentHashRequest) Descriptor() ([]byte, []int) {
	return file_remotesignerrpc_remotesigner_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveWhitelistPaymentHashRequest) GetPaymentHash() []byte {
	if x != nil {
		return x.PaymentHash
	}
	return nil
}

type RemoveWhitelistPaymentHashResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The returned bool is True if the payment hash was removed from the
	// whitelist.
	Removed bool `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
}

func (x *RemoveWhitelistPaymentHashResp) Reset() {
	*x = RemoveWhitelistPaymentHashResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveWhitelistPaymentHashResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWhitelistPaymentHashResp) ProtoMessage() {}

func (x *RemoveWhitelistPaymentHashResp) ProtoReflect() protoreflect.Message {
	mi := &file_remotesignerrpc_remotesigner_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWhitelistPaymentHashResp.ProtoReflect.Descriptor instead.
func (*RemoveWhitelistPaymentHashResp) Descriptor() ([]byte, []int) {
	return file_remotesignerrpc_remotesigner_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveWhitelistPaymentHashResp) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

var File_remotesignerrpc_remotesigner_proto protoreflect.FileDescriptor

var file_remotesignerrpc_remotesigner_proto_rawDesc = []byte{
	0x0a, 0x22, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x72, 0x70,
	0x63, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x72, 0x72, 0x70, 0x63, 0x22, 0x4b, 0x0a, 0x17, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69,
	0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x1d, 0x0a, 0x1b, 0x57, 0x68,
	0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x18, 0x57, 0x68, 0x69,
	0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x1d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x57, 0x68, 0x69,
	0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x36,
	0x0a, 0x1a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73,
	0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x22, 0x58, 0x0a, 0x1b, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c,
	0x69, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x1a, 0x0a, 0x18, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x22, 0x21, 0x0a, 0x1f,
	0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x45, 0x0a, 0x1c, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x25, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x22, 0x46, 0x0a, 0x21, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x22, 0x3a,
	0x0a, 0x1e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73,
	0x74, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x32, 0xd1, 0x05, 0x0a, 0x0c, 0x52,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x12, 0x63, 0x0a, 0x10, 0x57,
	0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x28, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x72, 0x70,
	0x63, 0x2e, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x68, 0x69, 0x74,
	0x65, 0x6c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x6f, 0x0a, 0x14, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x2c, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x68, 0x69, 0x74, 0x65,
	0x6c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x73,
	0x69, 0x67, 0x6e, 0x65, 0x72, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69,
	0x73, 0x74, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x77, 0x0a, 0x18, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x57, 0x68, 0x69, 0x74, 0x65,
	0x6c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2e, 0x2e,
	0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x72, 0x70, 0x63, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e,
	0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x72, 0x70, 0x63, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x6f, 0x0a, 0x14, 0x57, 0x68,
	0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x2c, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x72, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x29, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x72,
	0x70, 0x63, 0x2e, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x7b, 0x0a, 0x18, 0x57,
	0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x12, 0x30, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c,
	0x69, 0x73, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x68, 0x69, 0x74,
	0x65, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61,
	0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x83, 0x01, 0x0a, 0x1c, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x32, 0x2e, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e,
	0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x72, 0x70, 0x63, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x50,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x42, 0x37,
	0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x6e, 0x69, 0x6e, 0x67, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x6c, 0x6e,
	0x64, 0x2f, 0x6c, 0x6e, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x73, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_remotesignerrpc_remotesigner_proto_rawDescOnce sync.Once
	file_remotesignerrpc_remotesigner_proto_rawDescData = file_remotesignerrpc_remotesigner_proto_rawDesc
)

func file_remotesignerrpc_remotesigner_proto_rawDescGZIP() []byte {
	file_remotesignerrpc_remotesigner_proto_rawDescOnce.Do(func() {
		file_remotesignerrpc_remotesigner_proto_rawDescData = protoimpl.X.CompressGZIP(file_remotesignerrpc_remotesigner_proto_rawDescData)
	})
	return file_remotesignerrpc_remotesigner_proto_rawDescData
}

var file_remotesignerrpc_remotesigner_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_remotesignerrpc_remotesigner_proto_goTypes = []interface{}{
	(*WhitelistAddressRequest)(nil),           // 0: remotesignerrpc.WhitelistAddressRequest
	(*WhitelistAddressResp)(nil),              // 1: remotesignerrpc.WhitelistAddressResp
	(*WhitelistedAddressesRequest)(nil),       // 2: remotesignerrpc.WhitelistedAddressesRequest
	(*WhitelistedAddressesResp)(nil),          // 3: remotesignerrpc.WhitelistedAddressesResp
	(*RemoveWhitelistAddressRequest)(nil),     // 4: remotesignerrpc.RemoveWhitelistAddressRequest
	(*RemoveWhitelistAddressResp)(nil),        // 5: remotesignerrpc.RemoveWhitelistAddressResp
	(*WhitelistPaymentHashRequest)(nil),       // 6: remotesignerrpc.WhitelistPaymentHashRequest
	(*WhitelistPaymentHashResp)(nil),          // 7: remotesignerrpc.WhitelistPaymentHashResp
	(*WhitelistedPaymentHashesRequest)(nil),   // 8: remotesignerrpc.WhitelistedPaymentHashesRequest
	(*WhitelistedPaymentHashesResp)(nil),      // 9: remotesignerrpc.WhitelistedPaymentHashesResp
	(*RemoveWhitelistPaymentHashRequest)(nil), // 10: remotesignerrpc.RemoveWhitelistPaymentHashRequest
	(*RemoveWhitelistPaymentHashResp)(nil),    // 11: remotesignerrpc.RemoveWhitelistPaymentHashResp
}
var file_remotesignerrpc_remotesigner_proto_depIdxs = []int32{
	0,  // 0: remotesignerrpc.RemoteSigner.WhitelistAddress:input_type -> remotesignerrpc.WhitelistAddressRequest
	2,  // 1: remotesignerrpc.RemoteSigner.WhitelistedAddresses:input_type -> remotesignerrpc.WhitelistedAddressesRequest
	4,  // 2: remotesignerrpc.RemoteSigner.RemoveWhitelistedAddress:input_type -> remotesignerrpc.RemoveWhitelistAddressRequest
	6,  // 3: remotesignerrpc.RemoteSigner.WhitelistPaymentHash:input_type -> remotesignerrpc.WhitelistPaymentHashRequest
	8,  // 4: remotesignerrpc.RemoteSigner.WhitelistedPaymentHashes:input_type -> remotesignerrpc.WhitelistedPaymentHashesRequest
	10, // 5: remotesignerrpc.RemoteSigner.RemoveWhitelistedPaymentHash:input_type -> remotesignerrpc.RemoveWhitelistPaymentHashRequest
	1,  // 6: remotesignerrpc.RemoteSigner.WhitelistAddress:output_type -> remotesignerrpc.WhitelistAddressResp
	3,  // 7: remotesignerrpc.RemoteSigner.WhitelistedAddresses:output_type -> remotesignerrpc.WhitelistedAddressesResp
	5,  // 8: remotesignerrpc.RemoteSigner.RemoveWhitelistedAddress:output_type -> remotesignerrpc.RemoveWhitelistAddressResp
	7,  // 9: remotesignerrpc.RemoteSigner.WhitelistPaymentHash:output_type -> remotesignerrpc.WhitelistPaymentHashResp
	9,  // 10: remotesignerrpc.RemoteSigner.WhitelistedPaymentHashes:output_type -> remotesignerrpc.WhitelistedPaymentHashesResp
	11, // 11: remotesignerrpc.RemoteSigner.RemoveWhitelistedPaymentHash:output_type -> remotesignerrpc.RemoveWhitelistPaymentHashResp
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_remotesignerrpc_remotesigner_proto_init() }
func file_remotesignerrpc_remotesigner_proto_init() {
	if File_remotesignerrpc_remotesigner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_remotesignerrpc_remotesigner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhitelistAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remotesignerrpc_remotesigner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhitelistAddressResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remotesignerrpc_remotesigner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhitelistedAddressesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remotesignerrpc_remotesigner_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhitelistedAddressesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remotesignerrpc_remotesigner_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveWhitelistAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remotesignerrpc_remotesigner_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveWhitelistAddressResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remotesignerrpc_remotesigner_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhitelistPaymentHashRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remotesignerrpc_remotesigner_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhitelistPaymentHashResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remotesignerrpc_remotesigner_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhitelistedPaymentHashesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remotesignerrpc_remotesigner_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhitelistedPaymentHashesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remotesignerrpc_remotesigner_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveWhitelistPaymentHashRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remotesignerrpc_remotesigner_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveWhitelistPaymentHashResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_remotesignerrpc_remotesigner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remotesignerrpc_remotesigner_proto_goTypes,
		DependencyIndexes: file_remotesignerrpc_remotesigner_proto_depIdxs,
		MessageInfos:      file_remotesignerrpc_remotesigner_proto_msgTypes,
	}.Build()
	File_remotesignerrpc_remotesigner_proto = out.File
	file_remotesignerrpc_remotesigner_proto_rawDesc = nil
	file_remotesignerrpc_remotesigner_proto_goTypes = nil
	file_remotesignerrpc_remotesigner_proto_depIdxs = nil
}
